/*
 * SMS - OpenAPI 3.0
 *
 * A simple api for sending sms.
 *
 * API version: 1.0.1
 * Contact: ulysse.rousselet@callr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "/home/ulysse/code/go-server-server-generated/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
